//! # ducklake-orm-macros
//!
//! Procedural macros for `ducklake-orm`. This crate is not meant to be used
//! directly — import it via the re-export in `ducklake-orm`:
//!
//! ```toml
//! [dependencies]
//! ducklake-orm = "0.1"
//! ```
//!
//! Then use the derive macro:
//!
//! ```rust,ignore
//! use ducklake_orm::Table;
//!
//! #[derive(Table, Debug)]
//! #[ducklake(table = "sales", schema = "main")]
//! pub struct Sale {
//!     #[ducklake(primary_key)]
//!     pub id: i64,
//!     pub amount: f64,
//!     pub region: String,
//! }
//! ```

use proc_macro::TokenStream;
use proc_macro2::Span;
use quote::quote;
use syn::spanned::Spanned;
use syn::{Data, DeriveInput, Fields, Type, parse_macro_input};

/// Derive macro that implements [`DuckLakeTable`](ducklake_orm::schema::DuckLakeTable) for a
/// struct and generates type-safe column accessor methods used in query builders.
///
/// # Generated output
///
/// Given a struct:
///
/// ```rust,ignore
/// use ducklake_orm::Table;
///
/// #[derive(Table, Debug)]
/// #[ducklake(table = "sales", schema = "main")]
/// pub struct Sale {
///     #[ducklake(primary_key)]
///     pub id: i64,
///     pub amount: f64,
///     pub region: String,
/// }
/// ```
///
/// The macro emits:
///
/// 1. **`DuckLakeTable` implementation** with:
///    - `table_name()` → `"sales"`
///    - `schema_name()` → `"main"`
///    - `column_names()` → `&["id", "amount", "region"]` (SELECT columns)
///    - `insert_columns()` → same by default (INSERT columns)
///    - `from_row(row)` — deserialises a `duckdb::Row` by positional index
///    - `to_params(&self)` — serialises the struct's fields as DuckDB parameters
///
/// 2. **Static column accessor methods** on the struct itself:
///    - `Sale::id()`, `Sale::amount()`, `Sale::region()` → [`ColumnExpr`](ducklake_orm::query::ColumnExpr)
///
/// # Struct-level attributes: `#[ducklake(…)]`
///
/// | Attribute | Type | Default | Description |
/// |-----------|------|---------|-------------|
/// | `table = "name"` | string literal | struct name in `snake_case` | SQL table name |
/// | `schema = "name"` | string literal | `"main"` | SQL schema name |
/// | `rename_all = "…"` | string literal | *no renaming* | Apply a case conversion to every field's SQL column name |
///
/// Supported `rename_all` values:
///
/// | Value | Example (`firstName`/`SaleItem`) |
/// |-------|-------------------------------|
/// | `snake_case` | `first_name` / `sale_item` |
/// | `SCREAMING_SNAKE_CASE` | `FIRST_NAME` / `SALE_ITEM` |
/// | `kebab-case` | `first-name` / `sale-item` |
/// | `camelCase` | `firstName` / `saleItem` |
/// | `PascalCase` | `FirstName` / `SaleItem` |
/// | `lowercase` | `firstname` / `saleitem` |
/// | `UPPERCASE` | `FIRSTNAME` / `SALEITEM` |
///
/// ## Field-level attributes: `#[ducklake(…)]`
///
/// | Attribute | Effect |
/// |-----------|--------|
/// | `primary_key` | Documentation-only marker. |
/// | `column = "…"` | Override the SQL column name for this single field (takes priority over `rename_all`). |
/// | `skip_insert` | Excludes the field from `INSERT` (`insert_columns` + `to_params`) but keeps it in `SELECT`/`from_row`. Use for DB-generated columns (sequences, `DEFAULT CURRENT_TIMESTAMP`, …). |
/// | `skip` | Fully virtual field: excluded from `SELECT`, `INSERT`, and no column accessor is generated. Populated via [`Default`] in `from_row`. |
///
/// ## Examples
///
/// ### Column alias
///
/// ```rust,ignore
/// #[derive(Table)]
/// struct Sale {
///     // field `sold_at` maps to SQL column `created_timestamp`
///     #[ducklake(column = "created_timestamp")]
///     pub sold_at: String,
/// }
/// ```
///
/// ### `skip_insert` (DB-generated column)
///
/// ```rust,ignore
/// #[derive(Table)]
/// struct Sale {
///     #[ducklake(skip_insert)] // omitted from INSERT, generated by the DB
///     pub id: i64,
///     pub amount: f64,
/// }
/// ```
///
/// ### `skip` (virtual / computed field)
///
/// ```rust,ignore
/// #[derive(Table)]
/// struct Sale {
///     pub amount: f64,
///     #[ducklake(skip)] // not in DB; computed in Rust
///     pub label: String,
/// }
/// ```
///
/// ### `rename_all`
///
/// ```rust,ignore
/// #[derive(Table)]
/// #[ducklake(table = "users", rename_all = "snake_case")]
/// struct User {
///     pub id: i64,
///     pub firstName: String, // → first_name
/// }
/// ```
///
/// # Column order contract
///
/// The order of non-`skip` fields in the struct **must match** the column order
/// in the DuckDB `CREATE TABLE` statement, because `from_row` uses positional
/// (`row.get(0)`, `row.get(1)`, …) access. Fields marked `#[ducklake(skip)]`
/// are filled via [`Default`] and do not affect indexing.
///
/// # Errors at compile time
///
/// The macro emits a compile-time error if applied to:
///
/// - An `enum` or `union` (only structs are supported)
/// - A struct with tuple or unit fields (only named fields are supported)
/// - A field attribute with an unknown key
/// - A `rename_all` value that is not one of the supported case styles
#[proc_macro_derive(Table, attributes(ducklake))]
pub fn derive_table(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    let struct_name = &input.ident;

    // ── struct-level attributes ──────────────────────────────────────────────
    let default_table = convert_case(&struct_name.to_string(), Case::Snake);
    let mut table_name = default_table;
    let mut schema_name = "main".to_string();
    let mut rename_all: Option<Case> = None;

    for attr in &input.attrs {
        if !attr.path().is_ident("ducklake") {
            continue;
        }
        let _ = attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("table") {
                let value: syn::LitStr = meta.value()?.parse()?;
                table_name = value.value();
            } else if meta.path.is_ident("schema") {
                let value: syn::LitStr = meta.value()?.parse()?;
                schema_name = value.value();
            } else if meta.path.is_ident("rename_all") {
                let value: syn::LitStr = meta.value()?.parse()?;
                match parse_case(&value.value()) {
                    Some(c) => rename_all = Some(c),
                    None => {
                        return Err(syn::Error::new(
                            value.span(),
                            format!(
                                "unknown rename_all value `{}`; expected one of: \
                                 snake_case, camelCase, PascalCase, SCREAMING_SNAKE_CASE, \
                                 kebab-case, lowercase, UPPERCASE",
                                value.value()
                            ),
                        ));
                    }
                }
            }
            Ok(())
        });
    }

    // ── collect named fields ─────────────────────────────────────────────────
    let named_fields = match &input.data {
        Data::Struct(data) => match &data.fields {
            Fields::Named(fields) => &fields.named,
            _ => {
                return syn::Error::new(
                    Span::call_site(),
                    "#[derive(Table)] only supports structs with named fields",
                )
                .to_compile_error()
                .into();
            }
        },
        _ => {
            return syn::Error::new(Span::call_site(), "#[derive(Table)] only supports structs")
                .to_compile_error()
                .into();
        }
    };

    // ── per-field parsing ────────────────────────────────────────────────────
    #[derive(Default)]
    struct FieldAttrs {
        column: Option<String>,
        skip: bool,
        skip_insert: bool,
    }

    let mut fields: Vec<(syn::Ident, Type, FieldAttrs)> = Vec::new();
    for f in named_fields {
        let ident = f.ident.clone().expect("named field");
        let ty = f.ty.clone();
        let mut fa = FieldAttrs::default();

        for attr in &f.attrs {
            if !attr.path().is_ident("ducklake") {
                continue;
            }
            let _ = attr.parse_nested_meta(|meta| {
                if meta.path.is_ident("primary_key") {
                    // documentation-only for now
                } else if meta.path.is_ident("skip") {
                    fa.skip = true;
                } else if meta.path.is_ident("skip_insert") {
                    fa.skip_insert = true;
                } else if meta.path.is_ident("column") {
                    let value: syn::LitStr = meta.value()?.parse()?;
                    fa.column = Some(value.value());
                } else {
                    return Err(syn::Error::new(
                        meta.path.span(),
                        "unknown field attribute; expected one of: \
                         column = \"…\", skip, skip_insert, primary_key",
                    ));
                }
                Ok(())
            });
        }

        fields.push((ident, ty, fa));
    }

    // ── resolve SQL column name per field ────────────────────────────────────
    // Returns the SQL column name as a string literal token.
    let resolved: Vec<(syn::Ident, Type, String, bool, bool)> = fields
        .iter()
        .map(|(ident, ty, fa)| {
            let sql_name = match (&fa.column, rename_all) {
                (Some(custom), _) => custom.clone(),
                (None, Some(case)) => convert_case(&ident.to_string(), case),
                (None, None) => ident.to_string(),
            };
            (ident.clone(), ty.clone(), sql_name, fa.skip, fa.skip_insert)
        })
        .collect();

    // ── SELECT columns (skip excluded) ───────────────────────────────────────
    let select_columns: Vec<String> = resolved
        .iter()
        .filter(|(_, _, _, skip, _)| !*skip)
        .map(|(_, _, name, _, _)| name.clone())
        .collect();

    // ── INSERT columns (skip AND skip_insert excluded) ───────────────────────
    let insert_columns: Vec<String> = resolved
        .iter()
        .filter(|(_, _, _, skip, skip_insert)| !*skip && !*skip_insert)
        .map(|(_, _, name, _, _)| name.clone())
        .collect();

    // ── from_row: positional read for non-skip, Default for skip ─────────────
    let mut select_idx: usize = 0;
    let from_row_fields = resolved.iter().map(|(ident, ty, _, skip, _)| {
        if *skip {
            quote! {
                #ident: <#ty as ::std::default::Default>::default()
            }
        } else {
            let idx = select_idx;
            select_idx += 1;
            quote! {
                #ident: row.get(#idx)?
            }
        }
    });

    // ── to_params: matches insert_columns (skip AND skip_insert excluded) ────
    let to_params_fields = resolved
        .iter()
        .filter(|(_, _, _, skip, skip_insert)| !*skip && !*skip_insert)
        .map(|(ident, _, _, _, _)| {
            quote! {
                Box::new(self.#ident.clone()) as Box<dyn ::duckdb::types::ToSql>
            }
        });

    // ── column accessor methods (skip excluded) ──────────────────────────────
    let col_methods = resolved
        .iter()
        .filter(|(_, _, _, skip, _)| !*skip)
        .map(|(ident, _, sql_name, _, _)| {
            quote! {
                /// Returns a [`ColumnExpr`](::ducklake_orm::query::ColumnExpr) handle
                /// for this column, usable in `.filter(...)`, `.set(...)`,
                /// `.order_by(...)`, etc.
                pub fn #ident() -> ::ducklake_orm::query::ColumnExpr {
                    ::ducklake_orm::query::ColumnExpr::new(#sql_name)
                }
            }
        });

    let expanded = quote! {
        impl ::ducklake_orm::schema::DuckLakeTable for #struct_name {
            fn table_name() -> &'static str {
                #table_name
            }

            fn schema_name() -> &'static str {
                #schema_name
            }

            fn column_names() -> &'static [&'static str] {
                &[#(#select_columns),*]
            }

            fn insert_columns() -> &'static [&'static str] {
                &[#(#insert_columns),*]
            }

            fn from_row(row: &::duckdb::Row<'_>) -> ::duckdb::Result<Self> {
                Ok(Self {
                    #(#from_row_fields),*
                })
            }

            fn to_params(&self) -> Vec<Box<dyn ::duckdb::types::ToSql>> {
                vec![#(#to_params_fields),*]
            }
        }

        impl #struct_name {
            #(#col_methods)*
        }
    };

    TokenStream::from(expanded)
}

// ── case conversion ───────────────────────────────────────────────────────────

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Case {
    /// `snake_case`
    Snake,
    /// `SCREAMING_SNAKE_CASE`
    ScreamingSnake,
    /// `kebab-case`
    Kebab,
    /// `camelCase` (lower camelCase)
    Camel,
    /// `PascalCase` (UpperCamelCase)
    Pascal,
    /// `lowercase`
    Lower,
    /// `UPPERCASE`
    Upper,
}

fn parse_case(s: &str) -> Option<Case> {
    match s {
        "snake_case" => Some(Case::Snake),
        "SCREAMING_SNAKE_CASE" => Some(Case::ScreamingSnake),
        "kebab-case" => Some(Case::Kebab),
        "camelCase" => Some(Case::Camel),
        "PascalCase" => Some(Case::Pascal),
        "lowercase" => Some(Case::Lower),
        "UPPERCASE" => Some(Case::Upper),
        _ => None,
    }
}

/// Tokenize an identifier written in some case convention into words, recognising
/// runs of uppercase letters as acronyms (so `HTTPRequest` → `["HTTP", "Request"]`,
/// not `["H", "T", "T", "P", "Request"]`).
fn split_words(s: &str) -> Vec<String> {
    let chars: Vec<char> = s.chars().collect();
    let mut words = Vec::new();
    let mut current = String::new();

    let mut prev: Option<char> = None;
    for (i, &ch) in chars.iter().enumerate() {
        let next = chars.get(i + 1).copied();
        let is_sep = ch == '_' || ch == '-' || ch == ' ';
        if is_sep {
            if !current.is_empty() {
                words.push(std::mem::take(&mut current));
            }
            prev = None;
            continue;
        }

        let boundary = match prev {
            None => false,
            Some(p) => {
                // lower→Upper boundary: fooBar
                (p.is_lowercase() && ch.is_uppercase())
                // Upper→Upper→lower boundary: HTTPRequest (start of new word at last Upper)
                    || (p.is_uppercase() && ch.is_uppercase() && next.map_or(false, |n| n.is_lowercase()))
                // digit/letter boundary
                    || (p.is_ascii_digit() != ch.is_ascii_digit())
            }
        };
        if boundary && !current.is_empty() {
            words.push(std::mem::take(&mut current));
        }
        current.push(ch);
        prev = Some(ch);
    }
    if !current.is_empty() {
        words.push(current);
    }
    words
}

fn convert_case(s: &str, case: Case) -> String {
    let words = split_words(s);
    match case {
        Case::Lower => words.join("").to_ascii_lowercase(),
        Case::Upper => words.join("").to_ascii_uppercase(),
        Case::Snake => words
            .iter()
            .map(|w| w.to_ascii_lowercase())
            .collect::<Vec<_>>()
            .join("_"),
        Case::ScreamingSnake => words
            .iter()
            .map(|w| w.to_ascii_uppercase())
            .collect::<Vec<_>>()
            .join("_"),
        Case::Kebab => words
            .iter()
            .map(|w| w.to_ascii_lowercase())
            .collect::<Vec<_>>()
            .join("-"),
        Case::Camel => {
            let mut out = String::new();
            for (i, w) in words.iter().enumerate() {
                let lower = w.to_ascii_lowercase();
                if i == 0 {
                    out.push_str(&lower);
                } else {
                    let mut c = lower.chars();
                    if let Some(first) = c.next() {
                        out.push(first.to_ascii_uppercase());
                        out.extend(c);
                    }
                }
            }
            out
        }
        Case::Pascal => {
            let mut out = String::new();
            for w in words.iter() {
                let mut c = w.chars();
                if let Some(first) = c.next() {
                    out.push(first.to_ascii_uppercase());
                    out.extend(c.flat_map(|ch| ch.to_lowercase()));
                }
            }
            out
        }
    }
}
