//! The [`DuckLakeTable`] trait definition.

/// The core mapping trait between a Rust struct and a DuckLake / DuckDB table.
///
/// Every struct that represents a database table must implement this trait so
/// that the ORM can:
///
/// - Build the correct `SELECT … FROM catalog.schema.table` SQL.
/// - Deserialize each result row back into a value of `Self`.
/// - Serialize a value of `Self` into bound SQL parameters for `INSERT`.
///
/// ## Implementing via `#[derive(Table)]`
///
/// You should almost never implement this trait by hand. Use the `#[derive(Table)]`
/// macro instead:
///
/// ```rust,ignore
/// use ducklake_orm::Table;
///
/// #[derive(Table, Debug)]
/// #[ducklake(table = "products", schema = "inventory")]
/// pub struct Product {
///     #[ducklake(primary_key)]
///     pub id: i64,
///     pub name: String,
///     pub price: f64,
///     pub in_stock: bool,
/// }
/// ```
///
/// The macro generates:
///
/// ```rust,ignore
/// // (generated by #[derive(Table)] — shown here for documentation purposes)
/// impl DuckLakeTable for Product {
///     fn table_name()   -> &'static str { "products" }
///     fn schema_name()  -> &'static str { "inventory" }
///     fn column_names() -> &'static [&'static str] { &["id", "name", "price", "in_stock"] }
///
///     fn from_row(row: &duckdb::Row<'_>) -> duckdb::Result<Self> {
///         Ok(Self {
///             id:       row.get(0)?,
///             name:     row.get(1)?,
///             price:    row.get(2)?,
///             in_stock: row.get(3)?,
///         })
///     }
///
///     fn to_params(&self) -> Vec<Box<dyn duckdb::types::ToSql>> {
///         vec![
///             Box::new(self.id),
///             Box::new(self.name.clone()),
///             Box::new(self.price),
///             Box::new(self.in_stock),
///         ]
///     }
/// }
///
/// // Column accessor methods (also generated by the macro):
/// impl Product {
///     pub fn id()       -> ColumnExpr { ColumnExpr::new("id") }
///     pub fn name()     -> ColumnExpr { ColumnExpr::new("name") }
///     pub fn price()    -> ColumnExpr { ColumnExpr::new("price") }
///     pub fn in_stock() -> ColumnExpr { ColumnExpr::new("in_stock") }
/// }
/// ```
///
/// ## Manual implementation
///
/// You may implement this trait manually when:
///
/// - The column order in the `SELECT` result differs from struct field order.
/// - You need custom type conversions not covered by `duckdb`'s `FromSql` / `ToSql`.
/// - You are mapping a view or a computed query result, not a base table.
///
/// In all other cases, `#[derive(Table)]` is the recommended approach.
///
/// ## Column / field ordering contract
///
/// The slices returned by [`column_names`] and the indexing used in
/// [`from_row`] **must be consistent with each other and with the struct's
/// field order**. The ORM generates `SELECT col1, col2, …` using
/// `column_names()`, then calls `from_row` which reads column 0, 1, 2, … in
/// the same order. If they diverge you will get silently wrong data or a
/// runtime `duckdb::Error`.
///
/// [`column_names`]: DuckLakeTable::column_names
/// [`from_row`]: DuckLakeTable::from_row
pub trait DuckLakeTable: Sized {
    /// The bare SQL table name, without any schema or catalog prefix.
    ///
    /// For a table defined as `CREATE TABLE main.sales (…)` this should
    /// return `"sales"`. The schema and catalog are provided separately by
    /// [`schema_name`] and the catalog stored in the connection/pool.
    ///
    /// The `#[derive(Table)]` macro derives this from the `table` attribute:
    /// `#[ducklake(table = "sales")]`. If the attribute is omitted, the
    /// struct name is converted to `snake_case`.
    ///
    /// [`schema_name`]: DuckLakeTable::schema_name
    fn table_name() -> &'static str;

    /// The SQL schema (namespace) that contains the table.
    ///
    /// Defaults to `"main"` when using `#[derive(Table)]` without an
    /// explicit `#[ducklake(schema = "…")]` attribute.
    ///
    /// In DuckDB, the default schema for user tables is `main`. In DuckLake,
    /// you may have multiple schemas inside a catalog — for example:
    ///
    /// ```text
    /// ATTACH 'catalog.duckdb' AS lake (TYPE DUCKLAKE);
    /// -- tables live at: lake.<schema>.<table>
    /// ```
    fn schema_name() -> &'static str;

    /// The complete, ordered list of column names that appear in the SQL
    /// `SELECT` statement generated by the ORM.
    ///
    /// The `i`-th name in this slice **must** correspond to the `i`-th
    /// positional read in [`from_row`] (i.e. `row.get(i)`).
    ///
    /// Fields marked `#[ducklake(skip)]` are excluded from this list and from
    /// [`from_row`]'s positional indexing (they are populated via `Default`).
    /// Fields marked `#[ducklake(skip_insert)]` are **included** here (they are
    /// real DB columns), but excluded from [`insert_columns`] and [`to_params`].
    ///
    /// [`from_row`]: DuckLakeTable::from_row
    /// [`insert_columns`]: DuckLakeTable::insert_columns
    /// [`to_params`]: DuckLakeTable::to_params
    fn column_names() -> &'static [&'static str];

    /// The ordered list of column names that appear in the `INSERT` statement
    /// generated by the ORM.
    ///
    /// This must be consistent with [`to_params`]: the `i`-th column name here
    /// binds against the `i`-th entry returned by `to_params()`.
    ///
    /// The `#[derive(Table)]` macro populates this from the non-`skip`,
    /// non-`skip_insert` fields. Typically used to exclude database-generated
    /// columns (sequences, `DEFAULT CURRENT_TIMESTAMP`, server-assigned UUIDs,
    /// …) from `INSERT`.
    ///
    /// [`column_names`]: DuckLakeTable::column_names
    /// [`to_params`]: DuckLakeTable::to_params
    fn insert_columns() -> &'static [&'static str];

    /// Deserialize a single DuckDB result row into a value of `Self`.
    ///
    /// This method is called for every row returned by `SELECT` queries. It
    /// reads each column by positional index using `row.get(i)`, which relies
    /// on DuckDB's [`FromSql`](duckdb::types::FromSql) trait.
    ///
    /// ## Common `FromSql` mappings
    ///
    /// | Rust type   | DuckDB type  |
    /// |-------------|--------------|
    /// | `i64`       | `BIGINT`     |
    /// | `i32`       | `INTEGER`    |
    /// | `f64`       | `DOUBLE`     |
    /// | `f32`       | `FLOAT`      |
    /// | `String`    | `VARCHAR`    |
    /// | `bool`      | `BOOLEAN`    |
    /// | `Vec<u8>`   | `BLOB`       |
    /// | `Option<T>` | nullable `T` |
    ///
    /// ## Errors
    ///
    /// Returns a [`duckdb::Error`] if any column value cannot be converted to
    /// the expected Rust type (e.g. `NULL` into a non-`Option` field).
    fn from_row(row: &duckdb::Row<'_>) -> duckdb::Result<Self>;

    /// Serialize `self` into a vector of positional SQL parameters.
    ///
    /// This method is used by [`InsertBuilder`](crate::query::InsertBuilder)
    /// to bind each field value to the corresponding `$1`, `$2`, … placeholder
    /// in the generated `INSERT` statement.
    ///
    /// The order must match the order of [`column_names`].
    ///
    /// All field types must implement [`duckdb::types::ToSql`]. The
    /// `#[derive(Table)]` macro calls `.clone()` on every field, so all
    /// types must also implement [`Clone`].
    ///
    /// [`column_names`]: DuckLakeTable::column_names
    fn to_params(&self) -> Vec<Box<dyn duckdb::types::ToSql>>;
}
