use duckdb::types::ToSql;

/// Owned SQL value used as a bound parameter in WHERE clauses.
#[derive(Debug, Clone)]
pub enum SqlValue {
    Integer(i64),
    Real(f64),
    Text(String),
    Boolean(bool),
    Null,
}

impl ToSql for SqlValue {
    fn to_sql(&self) -> duckdb::Result<duckdb::types::ToSqlOutput<'_>> {
        use duckdb::types::{ToSqlOutput, Value};
        let v = match self {
            SqlValue::Integer(i) => Value::BigInt(*i),
            SqlValue::Real(f) => Value::Double(*f),
            SqlValue::Text(s) => Value::Text(s.clone()),
            SqlValue::Boolean(b) => Value::Boolean(*b),
            SqlValue::Null => Value::Null,
        };
        Ok(ToSqlOutput::Owned(v))
    }
}

impl From<i64> for SqlValue {
    fn from(v: i64) -> Self {
        SqlValue::Integer(v)
    }
}
impl From<i32> for SqlValue {
    fn from(v: i32) -> Self {
        SqlValue::Integer(v as i64)
    }
}
impl From<f64> for SqlValue {
    fn from(v: f64) -> Self {
        SqlValue::Real(v)
    }
}
impl From<f32> for SqlValue {
    fn from(v: f32) -> Self {
        SqlValue::Real(v as f64)
    }
}
impl From<String> for SqlValue {
    fn from(v: String) -> Self {
        SqlValue::Text(v)
    }
}
impl From<&str> for SqlValue {
    fn from(v: &str) -> Self {
        SqlValue::Text(v.to_string())
    }
}
impl From<bool> for SqlValue {
    fn from(v: bool) -> Self {
        SqlValue::Boolean(v)
    }
}

/// Type-safe handle to a column — returned by the column accessor methods
/// generated by `#[derive(Table)]` (e.g. `Sale::amount()`).
#[derive(Debug, Clone)]
pub struct ColumnExpr {
    pub(crate) name: &'static str,
}

impl ColumnExpr {
    pub fn new(name: &'static str) -> Self {
        Self { name }
    }

    pub fn eq<V: Into<SqlValue>>(self, val: V) -> FilterExpr {
        FilterExpr::Eq(self.name, val.into())
    }

    pub fn ne<V: Into<SqlValue>>(self, val: V) -> FilterExpr {
        FilterExpr::Ne(self.name, val.into())
    }

    pub fn gt<V: Into<SqlValue>>(self, val: V) -> FilterExpr {
        FilterExpr::Gt(self.name, val.into())
    }

    pub fn gte<V: Into<SqlValue>>(self, val: V) -> FilterExpr {
        FilterExpr::Gte(self.name, val.into())
    }

    pub fn lt<V: Into<SqlValue>>(self, val: V) -> FilterExpr {
        FilterExpr::Lt(self.name, val.into())
    }

    pub fn lte<V: Into<SqlValue>>(self, val: V) -> FilterExpr {
        FilterExpr::Lte(self.name, val.into())
    }

    pub fn like(self, pattern: impl Into<String>) -> FilterExpr {
        FilterExpr::Like(self.name, pattern.into())
    }

    pub fn between<V: Into<SqlValue>>(self, lo: V, hi: V) -> FilterExpr {
        FilterExpr::Between(self.name, lo.into(), hi.into())
    }

    pub fn is_null(self) -> FilterExpr {
        FilterExpr::IsNull(self.name)
    }

    pub fn is_not_null(self) -> FilterExpr {
        FilterExpr::IsNotNull(self.name)
    }

    pub fn asc(self) -> OrderExpr {
        OrderExpr { col: self.name, dir: OrderDir::Asc }
    }

    pub fn desc(self) -> OrderExpr {
        OrderExpr { col: self.name, dir: OrderDir::Desc }
    }
}

/// A predicate expression used in WHERE clauses.
#[derive(Debug, Clone)]
pub enum FilterExpr {
    Eq(&'static str, SqlValue),
    Ne(&'static str, SqlValue),
    Gt(&'static str, SqlValue),
    Gte(&'static str, SqlValue),
    Lt(&'static str, SqlValue),
    Lte(&'static str, SqlValue),
    Like(&'static str, String),
    Between(&'static str, SqlValue, SqlValue),
    IsNull(&'static str),
    IsNotNull(&'static str),
    And(Box<FilterExpr>, Box<FilterExpr>),
    Or(Box<FilterExpr>, Box<FilterExpr>),
}

impl FilterExpr {
    pub fn and(self, other: FilterExpr) -> FilterExpr {
        FilterExpr::And(Box::new(self), Box::new(other))
    }

    pub fn or(self, other: FilterExpr) -> FilterExpr {
        FilterExpr::Or(Box::new(self), Box::new(other))
    }
}

/// Build the SQL fragment and param list for a slice of filters.
/// `param_offset` is the 1-based index to start numbering `$N` placeholders.
pub fn build_where_clause(filters: &[FilterExpr], param_offset: usize) -> (String, Vec<SqlValue>) {
    let mut params = Vec::new();
    let parts: Vec<String> = filters
        .iter()
        .map(|f| render_filter(f, &mut params, param_offset))
        .collect();
    (parts.join(" AND "), params)
}

fn render_filter(expr: &FilterExpr, params: &mut Vec<SqlValue>, offset: usize) -> String {
    match expr {
        FilterExpr::Eq(col, val) => {
            params.push(val.clone());
            format!("{col} = ${}", offset + params.len() - 1)
        }
        FilterExpr::Ne(col, val) => {
            params.push(val.clone());
            format!("{col} != ${}", offset + params.len() - 1)
        }
        FilterExpr::Gt(col, val) => {
            params.push(val.clone());
            format!("{col} > ${}", offset + params.len() - 1)
        }
        FilterExpr::Gte(col, val) => {
            params.push(val.clone());
            format!("{col} >= ${}", offset + params.len() - 1)
        }
        FilterExpr::Lt(col, val) => {
            params.push(val.clone());
            format!("{col} < ${}", offset + params.len() - 1)
        }
        FilterExpr::Lte(col, val) => {
            params.push(val.clone());
            format!("{col} <= ${}", offset + params.len() - 1)
        }
        FilterExpr::Like(col, pattern) => {
            params.push(SqlValue::Text(pattern.clone()));
            format!("{col} LIKE ${}", offset + params.len() - 1)
        }
        FilterExpr::Between(col, lo, hi) => {
            params.push(lo.clone());
            let lo_idx = offset + params.len() - 1;
            params.push(hi.clone());
            let hi_idx = offset + params.len() - 1;
            format!("{col} BETWEEN ${lo_idx} AND ${hi_idx}")
        }
        FilterExpr::IsNull(col) => format!("{col} IS NULL"),
        FilterExpr::IsNotNull(col) => format!("{col} IS NOT NULL"),
        FilterExpr::And(left, right) => {
            let l = render_filter(left, params, offset);
            let r = render_filter(right, params, offset);
            format!("({l} AND {r})")
        }
        FilterExpr::Or(left, right) => {
            let l = render_filter(left, params, offset);
            let r = render_filter(right, params, offset);
            format!("({l} OR {r})")
        }
    }
}

/// An ORDER BY expression produced by `ColumnExpr::asc()` / `ColumnExpr::desc()`.
#[derive(Debug, Clone)]
pub struct OrderExpr {
    pub(crate) col: &'static str,
    pub(crate) dir: OrderDir,
}

#[derive(Debug, Clone)]
pub enum OrderDir {
    Asc,
    Desc,
}

impl OrderExpr {
    pub fn to_sql_fragment(&self) -> String {
        let dir = match self.dir {
            OrderDir::Asc => "ASC",
            OrderDir::Desc => "DESC",
        };
        format!("{} {dir}", self.col)
    }
}
