//! Filter and ordering types for the query DSL.
//!
//! All public types in this module are produced by column accessor methods
//! generated by `#[derive(Table)]`. You rarely construct them directly.

use duckdb::types::ToSql;

/// An owned SQL parameter value that can be bound to a `$N` placeholder.
///
/// `SqlValue` is the common representation for any scalar value that appears
/// in a `WHERE`, `HAVING`, or `SET` clause. It is produced implicitly by
/// the `Into<SqlValue>` blanket implementations when you write, for example:
///
/// ```rust,ignore
/// Sale::amount().gt(100.0)  // 100.0 is converted to SqlValue::Real(100.0)
/// Sale::region().eq("EU")   // "EU"  is converted to SqlValue::Text("EU".into())
/// ```
///
/// ## Supported conversions (`From` implementations)
///
/// | Rust type | Variant |
/// |-----------|---------|
/// | `i16`, `i32`, `i64` | `Integer(i64)` |
/// | `f32`, `f64` | `Real(f64)` |
/// | `String`, `&str` | `Text(String)` |
/// | `bool` | `Boolean(bool)` |
#[derive(Debug, Clone)]
pub enum SqlValue {
    /// A 64-bit signed integer (`BIGINT` in DuckDB).
    ///
    /// Produced by `From<i64>`, `From<i32>`, and `From<i16>`.
    Integer(i64),
    /// A 64-bit floating-point number (`DOUBLE` in DuckDB).
    ///
    /// Produced by `From<f64>` and `From<f32>`.
    Real(f64),
    /// A UTF-8 string (`VARCHAR` in DuckDB).
    ///
    /// Produced by `From<String>` and `From<&str>`.
    Text(String),
    /// A boolean (`BOOLEAN` in DuckDB).
    ///
    /// Produced by `From<bool>`.
    Boolean(bool),
    /// SQL `NULL`.
    ///
    /// Construct this variant explicitly when you need to bind a NULL value.
    Null,
}

impl ToSql for SqlValue {
    fn to_sql(&self) -> duckdb::Result<duckdb::types::ToSqlOutput<'_>> {
        use duckdb::types::{ToSqlOutput, Value};
        let v = match self {
            SqlValue::Integer(i) => Value::BigInt(*i),
            SqlValue::Real(f) => Value::Double(*f),
            SqlValue::Text(s) => Value::Text(s.clone()),
            SqlValue::Boolean(b) => Value::Boolean(*b),
            SqlValue::Null => Value::Null,
        };
        Ok(ToSqlOutput::Owned(v))
    }
}

impl From<i64> for SqlValue {
    fn from(v: i64) -> Self {
        SqlValue::Integer(v)
    }
}
impl From<i32> for SqlValue {
    fn from(v: i32) -> Self {
        SqlValue::Integer(v as i64)
    }
}
impl From<i16> for SqlValue {
    fn from(v: i16) -> Self {
        SqlValue::Integer(v as i64)
    }
}
impl From<f64> for SqlValue {
    fn from(v: f64) -> Self {
        SqlValue::Real(v)
    }
}
impl From<f32> for SqlValue {
    fn from(v: f32) -> Self {
        SqlValue::Real(v as f64)
    }
}
impl From<String> for SqlValue {
    fn from(v: String) -> Self {
        SqlValue::Text(v)
    }
}
impl From<&str> for SqlValue {
    fn from(v: &str) -> Self {
        SqlValue::Text(v.to_string())
    }
}
impl From<bool> for SqlValue {
    fn from(v: bool) -> Self {
        SqlValue::Boolean(v)
    }
}

// ── ColumnExpr ────────────────────────────────────────────────────────────────

/// A compile-time handle to a single column of a [`DuckLakeTable`](crate::schema::DuckLakeTable).
///
/// `ColumnExpr` is produced by the static column accessor methods generated by
/// `#[derive(Table)]`. For example, given:
///
/// ```rust,ignore
/// #[derive(Table)]
/// #[ducklake(table = "sales")]
/// struct Sale { id: i64, amount: f64, region: String }
/// ```
///
/// the macro generates `Sale::id()`, `Sale::amount()`, and `Sale::region()`,
/// each of which returns a `ColumnExpr` carrying the column name.
///
/// ## Available operations
///
/// Call a comparison or ordering method on a `ColumnExpr` to get a
/// [`FilterExpr`] or [`OrderExpr`]:
///
/// ```rust,ignore
/// Sale::amount().gt(100.0)           // FilterExpr: amount > 100.0
/// Sale::region().eq("EU")            // FilterExpr: region = 'EU'
/// Sale::region().like("EU%")         // FilterExpr: region LIKE 'EU%'
/// Sale::amount().between(10.0, 50.0) // FilterExpr: amount BETWEEN 10 AND 50
/// Sale::amount().asc()               // OrderExpr:  amount ASC
/// Sale::amount().desc()              // OrderExpr:  amount DESC
/// ```
#[derive(Debug, Clone)]
pub struct ColumnExpr {
    pub(crate) name: &'static str,
}

impl ColumnExpr {
    /// Construct a `ColumnExpr` from a static column name string.
    ///
    /// This is called by the code generated by `#[derive(Table)]` and is
    /// rarely needed in user code.
    pub fn new(name: &'static str) -> Self {
        Self { name }
    }

    /// `col = $n` — equality test.
    ///
    /// ```rust,ignore
    /// Sale::region().eq("EU")   // WHERE region = 'EU'
    /// Sale::id().eq(42i64)      // WHERE id = 42
    /// ```
    pub fn eq<V: Into<SqlValue>>(self, val: V) -> FilterExpr {
        FilterExpr::Eq(self.name, val.into())
    }

    /// `col != $n` — inequality test.
    ///
    /// ```rust,ignore
    /// Sale::region().ne("EU")   // WHERE region != 'EU'
    /// ```
    pub fn ne<V: Into<SqlValue>>(self, val: V) -> FilterExpr {
        FilterExpr::Ne(self.name, val.into())
    }

    /// `col > $n` — strictly greater than.
    ///
    /// ```rust,ignore
    /// Sale::amount().gt(100.0)  // WHERE amount > 100.0
    /// ```
    pub fn gt<V: Into<SqlValue>>(self, val: V) -> FilterExpr {
        FilterExpr::Gt(self.name, val.into())
    }

    /// `col >= $n` — greater than or equal to.
    ///
    /// ```rust,ignore
    /// Sale::amount().gte(100.0)  // WHERE amount >= 100.0
    /// ```
    pub fn gte<V: Into<SqlValue>>(self, val: V) -> FilterExpr {
        FilterExpr::Gte(self.name, val.into())
    }

    /// `col < $n` — strictly less than.
    ///
    /// ```rust,ignore
    /// Sale::amount().lt(50.0)  // WHERE amount < 50.0
    /// ```
    pub fn lt<V: Into<SqlValue>>(self, val: V) -> FilterExpr {
        FilterExpr::Lt(self.name, val.into())
    }

    /// `col <= $n` — less than or equal to.
    ///
    /// ```rust,ignore
    /// Sale::amount().lte(50.0)  // WHERE amount <= 50.0
    /// ```
    pub fn lte<V: Into<SqlValue>>(self, val: V) -> FilterExpr {
        FilterExpr::Lte(self.name, val.into())
    }

    /// `col LIKE $n` — SQL pattern matching.
    ///
    /// Use `%` as a wildcard for any sequence of characters and `_` for a
    /// single character (standard SQL `LIKE` semantics).
    ///
    /// ```rust,ignore
    /// Sale::region().like("EU%")   // WHERE region LIKE 'EU%'
    /// Sale::region().like("%WEST") // WHERE region LIKE '%WEST'
    /// ```
    pub fn like(self, pattern: impl Into<String>) -> FilterExpr {
        FilterExpr::Like(self.name, pattern.into())
    }

    /// `col BETWEEN $lo AND $hi` — inclusive range test.
    ///
    /// Both endpoints are **inclusive** (SQL `BETWEEN` semantics).
    ///
    /// ```rust,ignore
    /// Sale::amount().between(50.0, 200.0)  // WHERE amount BETWEEN 50.0 AND 200.0
    /// ```
    pub fn between<V: Into<SqlValue>>(self, lo: V, hi: V) -> FilterExpr {
        FilterExpr::Between(self.name, lo.into(), hi.into())
    }

    /// `col IS NULL` — test for NULL.
    ///
    /// ```rust,ignore
    /// Sale::region().is_null()   // WHERE region IS NULL
    /// ```
    pub fn is_null(self) -> FilterExpr {
        FilterExpr::IsNull(self.name)
    }

    /// `col IS NOT NULL` — test for non-NULL.
    ///
    /// ```rust,ignore
    /// Sale::region().is_not_null()   // WHERE region IS NOT NULL
    /// ```
    pub fn is_not_null(self) -> FilterExpr {
        FilterExpr::IsNotNull(self.name)
    }

    /// `col IN ($1, $2, …)` — matches any value in the list.
    ///
    /// Accepts any iterator whose items implement `Into<SqlValue>`:
    ///
    /// ```rust,ignore
    /// Sale::region().in_(["EU", "UK", "US"])
    /// // SQL: region IN ($1, $2, $3)
    ///
    /// let ids: Vec<i64> = vec![1, 2, 3];
    /// Sale::id().in_(ids)
    /// // SQL: id IN ($1, $2, $3)
    /// ```
    ///
    /// Passing an **empty** iterator produces the SQL constant `(1=0)` (always
    /// false), because `IN ()` is invalid SQL.
    pub fn in_<V: Into<SqlValue>>(self, vals: impl IntoIterator<Item = V>) -> FilterExpr {
        FilterExpr::In(self.name, vals.into_iter().map(Into::into).collect())
    }

    /// `col NOT IN ($1, $2, …)` — matches rows whose column value is not in the list.
    ///
    /// ```rust,ignore
    /// Sale::region().not_in(["APAC", "LATAM"])
    /// // SQL: region NOT IN ($1, $2)
    /// ```
    ///
    /// Passing an **empty** iterator produces `(1=1)` (always true).
    pub fn not_in<V: Into<SqlValue>>(self, vals: impl IntoIterator<Item = V>) -> FilterExpr {
        FilterExpr::NotIn(self.name, vals.into_iter().map(Into::into).collect())
    }

    /// Produce an ascending `ORDER BY` expression.
    ///
    /// Pass the result to [`SelectBuilder::order_by`](crate::query::SelectBuilder::order_by):
    ///
    /// ```rust,ignore
    /// .order_by(Sale::amount().asc())   // ORDER BY amount ASC
    /// ```
    pub fn asc(self) -> OrderExpr {
        OrderExpr {
            col: self.name,
            dir: OrderDir::Asc,
        }
    }

    /// Produce a descending `ORDER BY` expression.
    ///
    /// Pass the result to [`SelectBuilder::order_by`](crate::query::SelectBuilder::order_by):
    ///
    /// ```rust,ignore
    /// .order_by(Sale::amount().desc())  // ORDER BY amount DESC
    /// ```
    pub fn desc(self) -> OrderExpr {
        OrderExpr {
            col: self.name,
            dir: OrderDir::Desc,
        }
    }
}

// ── FilterExpr ────────────────────────────────────────────────────────────────

/// A predicate tree that can appear in a `WHERE` or `HAVING` clause.
///
/// Each variant represents a single comparison or a logical combination of
/// comparisons. You almost never construct variants directly — use the methods
/// on [`ColumnExpr`] instead:
///
/// ```rust,ignore
/// Sale::amount().gt(100.0)                        // FilterExpr::Gt
/// Sale::amount().gt(100.0).and(Sale::region().eq("EU"))  // FilterExpr::And(Gt, Eq)
/// Sale::region().eq("EU").or(Sale::region().eq("UK"))    // FilterExpr::Or(Eq, Eq)
/// ```
///
/// ## Combining predicates
///
/// Use [`.and()`](FilterExpr::and) and [`.or()`](FilterExpr::or) to build
/// compound predicates. These methods consume both sides and wrap them in
/// `And` / `Or` nodes:
///
/// ```rust,ignore
/// let predicate = Sale::amount()
///     .gt(100.0)
///     .and(Sale::region().eq("EU").or(Sale::region().eq("UK")));
/// // SQL: (amount > $1 AND (region = $2 OR region = $3))
/// ```
#[derive(Debug, Clone)]
pub enum FilterExpr {
    /// `col = $n`
    Eq(&'static str, SqlValue),
    /// `col != $n`
    Ne(&'static str, SqlValue),
    /// `col > $n`
    Gt(&'static str, SqlValue),
    /// `col >= $n`
    Gte(&'static str, SqlValue),
    /// `col < $n`
    Lt(&'static str, SqlValue),
    /// `col <= $n`
    Lte(&'static str, SqlValue),
    /// `col LIKE $n`
    Like(&'static str, String),
    /// `col BETWEEN $lo AND $hi`
    Between(&'static str, SqlValue, SqlValue),
    /// `col IS NULL`
    IsNull(&'static str),
    /// `col IS NOT NULL`
    IsNotNull(&'static str),
    /// `col IN ($1, $2, …)` — produced by [`ColumnExpr::in_`].
    ///
    /// An empty `Vec` renders as `(1=0)` (always false).
    In(&'static str, Vec<SqlValue>),
    /// `col NOT IN ($1, $2, …)` — produced by [`ColumnExpr::not_in`].
    ///
    /// An empty `Vec` renders as `(1=1)` (always true).
    NotIn(&'static str, Vec<SqlValue>),
    /// `(left AND right)`
    And(Box<FilterExpr>, Box<FilterExpr>),
    /// `(left OR right)`
    Or(Box<FilterExpr>, Box<FilterExpr>),
}

impl FilterExpr {
    /// Combine `self` and `other` with a logical `AND`.
    ///
    /// The resulting SQL is `(self AND other)` with parentheses to ensure
    /// correct precedence when nested inside an `OR`.
    ///
    /// ```rust,ignore
    /// Sale::amount().gt(100.0).and(Sale::region().eq("EU"))
    /// // SQL: (amount > $1 AND region = $2)
    /// ```
    pub fn and(self, other: FilterExpr) -> FilterExpr {
        FilterExpr::And(Box::new(self), Box::new(other))
    }

    /// Combine `self` and `other` with a logical `OR`.
    ///
    /// The resulting SQL is `(self OR other)` with parentheses.
    ///
    /// ```rust,ignore
    /// Sale::region().eq("EU").or(Sale::region().eq("UK"))
    /// // SQL: (region = $1 OR region = $2)
    /// ```
    pub fn or(self, other: FilterExpr) -> FilterExpr {
        FilterExpr::Or(Box::new(self), Box::new(other))
    }
}

/// Build the SQL fragment and collect bound parameters for a slice of filters.
///
/// Each filter in `filters` is rendered to SQL and appended with ` AND `.
/// `start_idx` is the 1-based positional index for the first `$N` placeholder;
/// subsequent parameters increment from there so callers can compose multiple
/// clauses (e.g., a `WHERE` clause followed by a `HAVING` clause) without
/// parameter index collisions.
///
/// Returns a tuple of `(sql_fragment, parameters)`.
pub fn build_where_clause(filters: &[FilterExpr], start_idx: usize) -> (String, Vec<SqlValue>) {
    let mut params = Vec::new();
    let parts: Vec<String> = filters
        .iter()
        .map(|f| render_filter(f, &mut params, start_idx))
        .collect();
    (parts.join(" AND "), params)
}

pub(crate) fn render_filter(expr: &FilterExpr, params: &mut Vec<SqlValue>, start: usize) -> String {
    match expr {
        FilterExpr::Eq(c, v) => {
            params.push(v.clone());
            format!("{c} = ${}", start + params.len() - 1)
        }
        FilterExpr::Ne(c, v) => {
            params.push(v.clone());
            format!("{c} != ${}", start + params.len() - 1)
        }
        FilterExpr::Gt(c, v) => {
            params.push(v.clone());
            format!("{c} > ${}", start + params.len() - 1)
        }
        FilterExpr::Gte(c, v) => {
            params.push(v.clone());
            format!("{c} >= ${}", start + params.len() - 1)
        }
        FilterExpr::Lt(c, v) => {
            params.push(v.clone());
            format!("{c} < ${}", start + params.len() - 1)
        }
        FilterExpr::Lte(c, v) => {
            params.push(v.clone());
            format!("{c} <= ${}", start + params.len() - 1)
        }
        FilterExpr::Like(c, p) => {
            params.push(SqlValue::Text(p.clone()));
            format!("{c} LIKE ${}", start + params.len() - 1)
        }
        FilterExpr::Between(c, lo, hi) => {
            params.push(lo.clone());
            let li = start + params.len() - 1;
            params.push(hi.clone());
            let hi_idx = start + params.len() - 1;
            format!("{c} BETWEEN ${li} AND ${hi_idx}")
        }
        FilterExpr::IsNull(c) => format!("{c} IS NULL"),
        FilterExpr::IsNotNull(c) => format!("{c} IS NOT NULL"),
        FilterExpr::In(c, vals) => {
            if vals.is_empty() {
                return "(1=0)".to_string();
            }
            let placeholders: Vec<_> = vals
                .iter()
                .map(|v| {
                    params.push(v.clone());
                    format!("${}", start + params.len() - 1)
                })
                .collect();
            format!("{c} IN ({})", placeholders.join(", "))
        }
        FilterExpr::NotIn(c, vals) => {
            if vals.is_empty() {
                return "(1=1)".to_string();
            }
            let placeholders: Vec<_> = vals
                .iter()
                .map(|v| {
                    params.push(v.clone());
                    format!("${}", start + params.len() - 1)
                })
                .collect();
            format!("{c} NOT IN ({})", placeholders.join(", "))
        }
        FilterExpr::And(l, r) => {
            let ls = render_filter(l, params, start);
            let rs = render_filter(r, params, start);
            format!("({ls} AND {rs})")
        }
        FilterExpr::Or(l, r) => {
            let ls = render_filter(l, params, start);
            let rs = render_filter(r, params, start);
            format!("({ls} OR {rs})")
        }
    }
}

/// Convert a slice of [`SqlValue`]s into a `Vec<&dyn ToSql>` for use as
/// DuckDB query parameters.
///
/// This is an internal helper used by all query builders. The returned
/// references borrow from `params`, so `params` must outlive the returned
/// `Vec`.
pub(crate) fn params_to_refs(params: &[SqlValue]) -> Vec<&dyn ToSql> {
    params.iter().map(|v| v as &dyn ToSql).collect()
}

// ── OrderExpr / OrderDir ──────────────────────────────────────────────────────

/// An `ORDER BY col ASC|DESC` expression.
///
/// Produced by [`ColumnExpr::asc`] and [`ColumnExpr::desc`]. Pass it to
/// [`SelectBuilder::order_by`](crate::query::SelectBuilder::order_by):
///
/// ```rust,ignore
/// .order_by(Sale::amount().desc())  // ORDER BY amount DESC
/// .order_by(Sale::region().asc())   // … then ORDER BY region ASC (second call)
/// ```
///
/// Multiple `.order_by()` calls are applied in the order they are called,
/// producing `ORDER BY col1 DIR1, col2 DIR2, …`.
#[derive(Debug, Clone)]
pub struct OrderExpr {
    pub(crate) col: &'static str,
    pub(crate) dir: OrderDir,
}

/// The sort direction for an [`OrderExpr`].
#[derive(Debug, Clone)]
pub enum OrderDir {
    /// `ASC` — ascending order (smallest value first).
    Asc,
    /// `DESC` — descending order (largest value first).
    Desc,
}

impl OrderExpr {
    pub(crate) fn to_sql_fragment(&self) -> String {
        let dir = match self.dir {
            OrderDir::Asc => "ASC",
            OrderDir::Desc => "DESC",
        };
        format!("{} {dir}", self.col)
    }
}
