//! Fluent query builders and the filter / ordering DSL.
//!
//! This module contains all the types you chain together to build SQL queries:
//!
//! | Type | SQL statement | Entry point |
//! |------|--------------|-------------|
//! | [`SelectBuilder`] | `SELECT … FROM … WHERE … GROUP BY … ORDER BY … LIMIT …` | [`DuckLakeConnection::select`](crate::connection::DuckLakeConnection::select) |
//! | [`InsertBuilder`] | `INSERT INTO … VALUES (…)` | [`DuckLakeConnection::insert`](crate::connection::DuckLakeConnection::insert) |
//! | [`BulkInsertBuilder`] | Same, wrapped in `BEGIN` / `COMMIT` | [`DuckLakeConnection::insert_many`](crate::connection::DuckLakeConnection::insert_many) |
//! | [`UpdateBuilder`] | `UPDATE … SET … WHERE …` | [`DuckLakeConnection::update`](crate::connection::DuckLakeConnection::update) |
//! | [`DeleteBuilder`] | `DELETE FROM … WHERE …` | [`DuckLakeConnection::delete`](crate::connection::DuckLakeConnection::delete) |
//!
//! ## Filter DSL
//!
//! Column accessor methods generated by `#[derive(Table)]` (e.g. `Sale::amount()`,
//! `Sale::region()`) return a [`ColumnExpr`]. Call a comparison method on it to
//! get a [`FilterExpr`]:
//!
//! ```rust,ignore
//! // Single predicate
//! Sale::amount().gt(100.0)          // amount > 100.0
//! Sale::region().eq("EU")           // region = 'EU'
//! Sale::region().like("EU%")        // region LIKE 'EU%'
//! Sale::amount().between(50.0, 200.0) // amount BETWEEN 50 AND 200
//!
//! // Compound predicates
//! Sale::amount().gt(100.0).and(Sale::region().eq("EU"))
//! Sale::region().eq("EU").or(Sale::region().eq("UK"))
//! ```
//!
//! ## Ordering DSL
//!
//! [`ColumnExpr::asc`] and [`ColumnExpr::desc`] return an [`OrderExpr`] that
//! can be passed to [`SelectBuilder::order_by`]:
//!
//! ```rust,ignore
//! .order_by(Sale::amount().desc())
//! .order_by(Sale::region().asc())
//! ```

mod delete;
mod filter;
mod insert;
mod select;
mod update;

pub use delete::DeleteBuilder;
pub(crate) use filter::params_to_refs;
pub use filter::{ColumnExpr, FilterExpr, OrderDir, OrderExpr, SqlValue};
pub use insert::{BulkInsertBuilder, InsertBuilder, OnConflict};
pub use select::{SelectBuilder, SnapshotRef};
pub use update::UpdateBuilder;
